<?php

namespace UserFlowBundle\Repository;


use UserFlowBundle\Entity\LoginMessage;

/**
 * LoginMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginMessageRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findOneOrCreateByUser($user)
    {
        $entity = $this->findOneByUser($user);

        if (null === $entity)
        {
           $entity = new LoginMessage($user);
           $em = $this->getEntityManager();
           $em->persist($entity);
           $em->flush();
        }

        return $entity;
    }
    
    public function getUserState($user){
        $loginMessage = $this->findOneOrCreateByUser($user);
        return $loginMessage->getState();
    }
    
     public function setUserState($user, $state){
        $loginMessage = $this->findOneOrCreateByUser($user);
        $loginMessage->setState($state);
        $em = $this->getEntityManager();
        $em->persist($loginMessage);
        $em->flush();
    }
    
}
