framework:
    workflows:
        loginModal:
            type: state_machine
            supports:
                - UserFlowBundle\Entity\LoginMessage
            places:
                - show
                - hide
            transitions:
                user_logs_in:
                    from: hide
                    to: show
                message_shown:
                    from: show
                    to: hide
        article:
            supports:
                - AppBundle\Entity\Article
            places:
                - draft
                - wait_for_journalist
                - approved_by_journalist
                - wait_for_spellchecker
                - approved_by_spellchecker
                - published
            transitions:
                request_review:
                    from: draft
                    to:
                        - wait_for_journalist
                        - wait_for_spellchecker
                journalist_approval:
                    from: wait_for_journalist
                    to: approved_by_journalist
                spellchecker_approval:
                    from: wait_for_spellchecker
                    to: approved_by_spellchecker
                publish:
                    from:
                        - approved_by_journalist
                        - approved_by_spellchecker
                    to: published

        task:
            type: state_machine
            supports:
                - AppBundle\Entity\Task
            places:
                - backlog
                - in_progress
                - done
            transitions:
                processing:
                    from: backlog
                    to: in_progress
                done:
                    from: in_progress
                    to: done

        straight:
            supports:
                - stdClass # Just a hack
            places:
                - a
                - b
                - c
                - d
            transitions:
                t1:
                    from: a
                    to: b
                t2:
                    from: b
                    to: c
                t3:
                    from: c
                    to: d

        round_trip:
            supports:
                - stdClass # Just a hack
            places:
                - a
                - b
                - c
            transitions:
                t1:
                    from: a
                    to: b
                t2:
                    from: b
                    to: c
                t3:
                    from: c
                    to: a

        or:
            supports:
                - stdClass # Just a hack
            places:
                - a
                - b
                - c
                - d
            transitions:
                t1:
                    from: a
                    to: b
                t2:
                    from: a
                    to: c
                t3:
                    from: b
                    to: d
                t4:
                    from: c
                    to: d

        and:
            supports:
                - stdClass # Just a hack
            places:
                - a
                - b
                - c
                - d
                - e
                - f
            transitions:
                t1:
                    from: a
                    to: [b, c]
                t2:
                    from: b
                    to: d
                t3:
                    from: c
                    to: e
                t4:
                    from: [d, e]
                    to: f


        wtf:
            supports: stdClass # Just a hack
            places: [ a, b, c, d, e, f, g, h, i, j, k ]
            transitions:
                t1:
                    from: a
                    to: b
                t2:
                    from: b
                    to: c
                t3:
                    from: c
                    to: d
                t4:
                    from: b
                    to: e
                t5:
                    from: b
                    to: f
                t6:
                    from: [c, d]
                    to: [f, g]
                t7:
                    from: e
                    to: h
                t8:
                    from: [e, g, i]
                    to: h
                t9:
                    from: [f, g]
                    to: [i, j]
                t10:
                    from: h
                    to: k
